from src.scraper.interaction_crawl import parallel_crawl_interaction
from src.scraper.user_scaper import parallel_scrap_user_per_page
from src.scraper.problem_scraper import parallel_scrap_problem_per_page